spring:
  application:
    name: singlewood-provider
  datasource:
    url: jdbc:oracle:thin:@*.*.*.*/orcl
    username: ***
    password: ***
    driver-class-name: oracle.jdbc.driver.OracleDriver
db-config:
  defalut-config-list:
    - {db-type: mysql,driver-class-name: com.mysql.cj.jdbc.Driver, port: 3306, url-template: 'jdbc:mysql://{{IP}}:{{PORT}}/{{END_PARAM}}'}
    - {db-type: oracle,driver-class-name: oracle.jdbc.driver.OracleDriver, port: 1521, url-template: 'jdbc:oracle:thin:@{{IP}}:{{PORT}}/{{END_PARAM}}'}
    - {db-type: postgres,driver-class-name: org.postgresql.Driver, port: 3306, url-template: 'jdbc:postgresql://{{IP}}:{{PORT}}/{{END_PARAM}}'}
  read-config: true
  config-file-name: application.yml
  debugger: false